### ISSUE TITLE
TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by jeffbonhag** [Nerian/google-id-token#5]
Hi,
I'm translating a bit of Java code to Ruby to do server-side token id token validation:

    validator = GoogleIDToken::Validator.new
    id_token = 'ey...4k'
    audience = '9..1.apps.googleusercontent.com'
    client_id = '9..1.apps.googleusercontent.com'
    validator.check(id_token, audience, client_id)

This throws the following error:

    TypeError: no implicit conversion of String into Integer
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:110:in `[]'
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:110:in `block in check_cached_certs'
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:102:in `each'
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:102:in `detect'
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:102:in `check_cached_certs'
    	from /Library/Ruby/Gems/2.0.0/gems/google-id-token-1.2.0/lib/google-id-token.rb:69:in `check'

It seems like a change in the `jwt` gem has possibly broken `google-id-token`?  Is there an older version of that gem I can use?

**Comment by Nerian** [comment]
Hi,

Are you sure you are using this gem?

```
gem 'google-id-token', git: 'git@github.com:Nerian/google-id-token.git'
```

The git part is important, as this repo is a fork.

**Comment by jeffbonhag** [comment]
Hi @Nerian,

You're totally right.  Thanks for helping me out!

Also, it turns out that I can leave out the `client_id` argument, I only needed to do:

    validator.check(id_token, audience)

to get back the validation hash.

Thanks again for steering me in the right direction.
